[package]
name = "antarticaos"
version = "0.1.0"
authors = ["Esdras Tarsis <esdrastarsis@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
xargo = "0.3.8"
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
